# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderexecutor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13orderexecutor.proto\x12\rorderexecutor\" \n\x0cOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\" \n\rOrderResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\\\n\rOrderExecutor\x12K\n\x0c\x45xecuteOrder\x12\x1b.orderexecutor.OrderRequest\x1a\x1c.orderexecutor.OrderResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderexecutor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERREQUEST']._serialized_start=38
  _globals['_ORDERREQUEST']._serialized_end=70
  _globals['_ORDERRESPONSE']._serialized_start=72
  _globals['_ORDERRESPONSE']._serialized_end=104
  _globals['_ORDEREXECUTOR']._serialized_start=106
  _globals['_ORDEREXECUTOR']._serialized_end=198
# @@protoc_insertion_point(module_scope)
