# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"L\n\x14\x43heckUserDataRequest\x12\x0f\n\x07orderID\x18\x01 \x01(\t\x12#\n\x04user\x18\x02 \x01(\x0b\x32\x15.fraud_detection.User\"9\n\x15\x43heckUserDataResponse\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"P\n\x15\x46raudDetectionRequest\x12\x0f\n\x07orderID\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x03 \x01(\t\":\n\x16\x46raudDetectionResponse\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"6\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t2\xe8\x01\n\x0e\x46raudDetection\x12l\n\x17\x43heckCreditCardForFraud\x12&.fraud_detection.FraudDetectionRequest\x1a\'.fraud_detection.FraudDetectionResponse\"\x00\x12h\n\x15\x43heckUserDataForFraud\x12%.fraud_detection.CheckUserDataRequest\x1a&.fraud_detection.CheckUserDataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHECKUSERDATAREQUEST']._serialized_start=42
  _globals['_CHECKUSERDATAREQUEST']._serialized_end=118
  _globals['_CHECKUSERDATARESPONSE']._serialized_start=120
  _globals['_CHECKUSERDATARESPONSE']._serialized_end=177
  _globals['_FRAUDDETECTIONREQUEST']._serialized_start=179
  _globals['_FRAUDDETECTIONREQUEST']._serialized_end=259
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=261
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=319
  _globals['_USER']._serialized_start=321
  _globals['_USER']._serialized_end=375
  _globals['_FRAUDDETECTION']._serialized_start=378
  _globals['_FRAUDDETECTION']._serialized_end=610
# @@protoc_insertion_point(module_scope)
